//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет о сервере.
    /// </summary>
    // *** Start programmer edit section *** (ОтчетОСервере CustomAttributes)

    // *** End programmer edit section *** (ОтчетОСервере CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет о сервере")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчетОСервереE", new string[] {
            "Режим as \'Режим\'",
            "Расположение",
            "Серверная"})]
    [View("ОтчетОСервереL", new string[] {
            "Режим as \'Режим\'"})]
    public class ОтчетОСервере : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Prilozhenie_5.РежимСервера fРежим;
        
        private IIS.Prilozhenie_5.Серверная fСерверная;
        
        private IIS.Prilozhenie_5.Расположение fРасположение;
        
        // *** Start programmer edit section *** (ОтчетОСервере CustomMembers)

        // *** End programmer edit section *** (ОтчетОСервере CustomMembers)

        
        /// <summary>
        /// Режим.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОСервере.Режим CustomAttributes)

        // *** End programmer edit section *** (ОтчетОСервере.Режим CustomAttributes)
        public virtual IIS.Prilozhenie_5.РежимСервера Режим
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОСервере.Режим Get start)

                // *** End programmer edit section *** (ОтчетОСервере.Режим Get start)
                IIS.Prilozhenie_5.РежимСервера result = this.fРежим;
                // *** Start programmer edit section *** (ОтчетОСервере.Режим Get end)

                // *** End programmer edit section *** (ОтчетОСервере.Режим Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОСервере.Режим Set start)

                // *** End programmer edit section *** (ОтчетОСервере.Режим Set start)
                this.fРежим = value;
                // *** Start programmer edit section *** (ОтчетОСервере.Режим Set end)

                // *** End programmer edit section *** (ОтчетОСервере.Режим Set end)
            }
        }
        
        /// <summary>
        /// Отчет о сервере.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОСервере.Расположение CustomAttributes)

        // *** End programmer edit section *** (ОтчетОСервере.Расположение CustomAttributes)
        [PropertyStorage(new string[] {
                "Расположение"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_5.Расположение Расположение
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОСервере.Расположение Get start)

                // *** End programmer edit section *** (ОтчетОСервере.Расположение Get start)
                IIS.Prilozhenie_5.Расположение result = this.fРасположение;
                // *** Start programmer edit section *** (ОтчетОСервере.Расположение Get end)

                // *** End programmer edit section *** (ОтчетОСервере.Расположение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОСервере.Расположение Set start)

                // *** End programmer edit section *** (ОтчетОСервере.Расположение Set start)
                this.fРасположение = value;
                // *** Start programmer edit section *** (ОтчетОСервере.Расположение Set end)

                // *** End programmer edit section *** (ОтчетОСервере.Расположение Set end)
            }
        }
        
        /// <summary>
        /// Отчет о сервере.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОСервере.Серверная CustomAttributes)

        // *** End programmer edit section *** (ОтчетОСервере.Серверная CustomAttributes)
        [PropertyStorage(new string[] {
                "Серверная"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_5.Серверная Серверная
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОСервере.Серверная Get start)

                // *** End programmer edit section *** (ОтчетОСервере.Серверная Get start)
                IIS.Prilozhenie_5.Серверная result = this.fСерверная;
                // *** Start programmer edit section *** (ОтчетОСервере.Серверная Get end)

                // *** End programmer edit section *** (ОтчетОСервере.Серверная Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОСервере.Серверная Set start)

                // *** End programmer edit section *** (ОтчетОСервере.Серверная Set start)
                this.fСерверная = value;
                // *** Start programmer edit section *** (ОтчетОСервере.Серверная Set end)

                // *** End programmer edit section *** (ОтчетОСервере.Серверная Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчетОСервереE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОСервереE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОСервереE", typeof(IIS.Prilozhenie_5.ОтчетОСервере));
                }
            }
            
            /// <summary>
            /// "ОтчетОСервереL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОСервереL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОСервереL", typeof(IIS.Prilozhenie_5.ОтчетОСервере));
                }
            }
        }
    }
}
